<?php

/** @var \Magento\GenericForm\Block\ContactForm $block */

$helper = $this->helper('Azra\GenericForm\Helper\Data');
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="request-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')); ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo $block->escapeHtml(__('Request information')); ?></span></legend><br />
        <div class="fieldset row">
            <div class="fields col-md-12">
              <div class="field name required">
                  <label class="label" for="form_name"><span><?php echo $block->escapeHtml(__('Name')); ?></span></label>
                  <div class="control">
                      <input name="form_name" id="form_name" title="<?php echo $block->escapeHtml(__('Name')); ?>" value="<?php echo $block->escapeHtml($helper->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                  </div>
              </div>
              <div class="field lastname required">
                  <label class="label" for="form_surname"><span><?php echo $block->escapeHtml(__('Last name')); ?></span></label>
                  <div class="control">
                      <input name="form_surname" id="form_surname" title="<?php echo $block->escapeHtml(__('Last name')); ?>" value="<?php echo $block->escapeHtml($helper->getUserLastName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                  </div>
              </div>
              <div class="field denomination">
                  <label class="label" for="form_denomination"><span><?php echo $block->escapeHtml(__('Company name')); ?></span></label>
                  <div class="control">
                      <input name="form_denomination" id="form_denomination" title="<?php echo $block->escapeHtml(__('Company name')); ?>" value="" class="input-text" type="text" />
                  </div>
              </div>
              <div class="field city">
                  <label class="label" for="form_city"><span><?php echo $block->escapeHtml(__('City')); ?></span></label>
                  <div class="control">
                      <input name="form_city" id="form_city" title="<?php echo $block->escapeHtml(__('City')); ?>" value="" class="input-text" type="text" />
                  </div>
              </div>
              <div class="field province">
                  <label class="label" for="form_province"><span><?php echo $block->escapeHtml(__('Province')); ?></span></label>
                  <div class="control">
                      <input name="form_province" id="form_province" title="<?php echo $block->escapeHtml(__('Province')); ?>" value="" class="input-text" type="text" />
                  </div>
              </div>
              <div class="field telephone">
                  <label class="label" for="form_telephone"><span><?php echo $block->escapeHtml(__('Phone')); ?></span></label>
                  <div class="control">
                      <input name="form_telephone" id="form_telephone" title="<?php echo $block->escapeHtml(__('Phone')); ?>" value="" class="input-text" type="text" />
                  </div>
              </div>
              <div class="field email required">
                  <label class="label" for="form_email"><span><?php echo $block->escapeHtml(__('Email')); ?></span></label>
                  <div class="control">
                      <input name="form_email" id="form_email" title="<?php echo $block->escapeHtml(__('Email')); ?>" value="<?php echo $block->escapeHtml($helper->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                  </div>
              </div>
              <?php if ($helper->getCurrentProduct()): ?>
              <div class="field product required">
                  <label class="label" for="form_product"><span><?php echo $block->escapeHtml(__('Product name')) ?></span></label>
                  <div class="control">
                      <input name="form_product" id="form_product" title="<?php echo $block->escapeHtml(__('Product name')) ?>" value="<?php echo $block->escapeHtml($helper->getCurrentProductName()) ?>" class="input-text" type="text" readonly="true" data-validate="{required:true}"/>
                  </div>
              </div>
              <?php endif; ?>
              <div class="field comment required">
                  <label class="label" for="form_comment"><span><?php echo $block->escapeHtml(__('Comment')); ?></span></label>
                  <div class="control">
                      <textarea name="form_comment" id="form_comment" title="<?php echo $block->escapeHtml(__('Comment')); ?>" class="input-text" cols="5" rows="8" data-validate="{required:true}"></textarea>
                  </div>
              </div>
              <div class="field choice accept-privacy required">
                  <label class="label" for="form_accept_privacy_text"><span><?php echo $block->escapeHtml(__('Privacy text')); ?></span></label>
                  <div class="control">
                      <textarea name="form_accept_privacy_text" readonly="true" id="form_accept_privacy_text" title="<?php echo $block->escapeHtml(__('Privacy text')); ?>" class="input-text" cols="5" rows="8"><?php echo $block->escapeHtml($helper->getPrivacyText()); ?></textarea>
                  </div>
                  <input name="form_accept_privacy" id="form_accept_privacy" title="<?php echo __('Authorization for data processing') ?>" class="checkbox" type="checkbox" data-validate="{required:true}"/>
                  <label class="label" for="form_accept_privacy"><span><?php echo __('Authorization for data processing') ?></span></label>
              </div>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <?php if ($helper->getCurrentProduct()): ?>
                <input type="hidden" name="product_sku" id="hideit" value="<?php echo $block->escapeHtml($helper->getCurrentProduct()->getSku()); ?>" />
            <?php endif ?>
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>

<script>
    require(["jquery","mage/mage"], function($)
    {
        //error placement for radio button
        var dataForm = $('#request-form');
        dataForm.mage('validation', {
            errorPlacement: function(error, element) {
                if (element.hasClass('checkbox')) {
                    error.appendTo('.field.choice');
                } else {
                    element.after(error);
                }
            }
        });

    });
</script>
